name: Build Flutter App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK (Android)
      run: flutter build apk --release

    - name: Build App Bundle (Android)
      run: flutter build appbundle --release

    - name: Archive Build Outputs
      uses: actions/upload-artifact@v3
      with:
        name: build-outputs
        path: build/

